/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthVerifyRouteImport } from './routes/api/auth/verify'
import { Route as ApiP2pSignalRouteImport } from './routes/api/p2p/signal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiAuthVerifyRoute = ApiAuthVerifyRouteImport.update({
  id: '/api/auth/verify',
  path: '/api/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiP2pSignalRoute = ApiP2pSignalRouteImport.update({
  id: '/api/p2p/signal',
  path: '/api/p2p/signal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/p2p/signal': typeof ApiP2pSignalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/p2p/signal': typeof ApiP2pSignalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/p2p/signal': typeof ApiP2pSignalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/auth/verify' | '/api/p2p/signal'
  fileRoutesByTo: FileRoutesByTo
  fileRoutesById: FileRoutesById
  to: '/' | '/api/auth/verify' | '/api/p2p/signal'
  id: '__root__' | '/' | '/api/auth/verify' | '/api/p2p/signal'
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAuthVerifyRoute: typeof ApiAuthVerifyRoute
  ApiP2pSignalRoute: typeof ApiP2pSignalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/verify': {
      id: '/api/auth/verify'
      path: '/api/auth/verify'
      fullPath: '/api/auth/verify'
      preLoaderRoute: typeof ApiAuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/p2p/signal': {
      id: '/api/p2p/signal'
      path: '/api/p2p/signal'
      fullPath: '/api/p2p/signal'
      preLoaderRoute: typeof ApiP2pSignalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAuthVerifyRoute: ApiAuthVerifyRoute,
  ApiP2pSignalRoute: ApiP2pSignalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
