/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAssetsEnrollRouteImport } from './routes/api/assets/enroll'
import { Route as ApiAssetsHeartbeatRouteImport } from './routes/api/assets/heartbeat'
import { Route as ApiAssetsLiveRouteImport } from './routes/api/assets/live'
import { Route as ApiAuthVerifyRouteImport } from './routes/api/auth/verify'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthStartRouteImport } from './routes/api/auth/start'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as ApiOnboardingDomainVerifyRouteImport } from './routes/api/onboarding/domain/verify'
import { Route as ApiP2pSignalRouteImport } from './routes/api/p2p/signal'
import { Route as ApiP2pTokenRouteImport } from './routes/api/p2p/token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiAuthStartRoute = ApiAuthStartRouteImport.update({
  id: '/api/auth/start',
  path: '/api/auth/start',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiAssetsEnrollRoute = ApiAssetsEnrollRouteImport.update({ id: '/api/assets/enroll', path: '/api/assets/enroll', getParentRoute: () => rootRouteImport } as any)
const ApiAssetsHeartbeatRoute = ApiAssetsHeartbeatRouteImport.update({ id: '/api/assets/heartbeat', path: '/api/assets/heartbeat', getParentRoute: () => rootRouteImport } as any)
const ApiAssetsLiveRoute = ApiAssetsLiveRouteImport.update({ id: '/api/assets/live', path: '/api/assets/live', getParentRoute: () => rootRouteImport } as any)

const ApiAuthVerifyRoute = ApiAuthVerifyRouteImport.update({
  id: '/api/auth/verify',
  path: '/api/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiOnboardingDomainVerifyRoute = ApiOnboardingDomainVerifyRouteImport.update({
  id: '/api/onboarding/domain/verify',
  path: '/api/onboarding/domain/verify',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiP2pTokenRoute = ApiP2pTokenRouteImport.update({
  id: '/api/p2p/token',
  path: '/api/p2p/token',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiP2pSignalRoute = ApiP2pSignalRouteImport.update({
  id: '/api/p2p/signal',
  path: '/api/p2p/signal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/auth/start': typeof ApiAuthStartRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/assets/enroll': typeof ApiAssetsEnrollRoute
  '/api/assets/heartbeat': typeof ApiAssetsHeartbeatRoute
  '/api/assets/live': typeof ApiAssetsLiveRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/onboarding/domain/verify': typeof ApiOnboardingDomainVerifyRoute
  '/api/p2p/signal': typeof ApiP2pSignalRoute
  '/api/p2p/token': typeof ApiP2pTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/onboarding/domain/verify': typeof ApiOnboardingDomainVerifyRoute
  '/api/p2p/signal': typeof ApiP2pSignalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/onboarding/domain/verify': typeof ApiOnboardingDomainVerifyRoute
  '/api/p2p/signal': typeof ApiP2pSignalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/assets/enroll' | '/api/assets/heartbeat' | '/api/assets/live' | '/api/auth/start' | '/api/auth/callback' | '/api/auth/verify' | '/api/onboarding/domain/verify' | '/api/p2p/signal' | '/api/p2p/token'
  fileRoutesByTo: FileRoutesByTo
  fileRoutesById: FileRoutesById
  to: '/' | '/api/assets/enroll' | '/api/assets/heartbeat' | '/api/assets/live' | '/api/auth/start' | '/api/auth/callback' | '/api/auth/verify' | '/api/onboarding/domain/verify' | '/api/p2p/signal' | '/api/p2p/token'
  id: '__root__' | '/' | '/api/assets/enroll' | '/api/assets/heartbeat' | '/api/assets/live' | '/api/auth/start' | '/api/auth/callback' | '/api/auth/verify' | '/api/onboarding/domain/verify' | '/api/p2p/signal' | '/api/p2p/token'
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAuthStartRoute: typeof ApiAuthStartRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAssetsEnrollRoute: typeof ApiAssetsEnrollRoute
  ApiAssetsHeartbeatRoute: typeof ApiAssetsHeartbeatRoute
  ApiAssetsLiveRoute: typeof ApiAssetsLiveRoute
  ApiAuthVerifyRoute: typeof ApiAuthVerifyRoute
  ApiOnboardingDomainVerifyRoute: typeof ApiOnboardingDomainVerifyRoute
  ApiP2pSignalRoute: typeof ApiP2pSignalRoute
  ApiP2pTokenRoute: typeof ApiP2pTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/start': {
      id: '/api/auth/start'
      path: '/api/auth/start'
      fullPath: '/api/auth/start'
      preLoaderRoute: typeof ApiAuthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/enroll': { id: '/api/assets/enroll', path: '/api/assets/enroll', fullPath: '/api/assets/enroll', preLoaderRoute: typeof ApiAssetsEnrollRouteImport, parentRoute: typeof rootRouteImport }
    '/api/assets/heartbeat': { id: '/api/assets/heartbeat', path: '/api/assets/heartbeat', fullPath: '/api/assets/heartbeat', preLoaderRoute: typeof ApiAssetsHeartbeatRouteImport, parentRoute: typeof rootRouteImport }
    '/api/assets/live': { id: '/api/assets/live', path: '/api/assets/live', fullPath: '/api/assets/live', preLoaderRoute: typeof ApiAssetsLiveRouteImport, parentRoute: typeof rootRouteImport }
    '/api/auth/verify': {
      id: '/api/auth/verify'
      path: '/api/auth/verify'
      fullPath: '/api/auth/verify'
      preLoaderRoute: typeof ApiAuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/domain/verify': {
      id: '/api/onboarding/domain/verify'
      path: '/api/onboarding/domain/verify'
      fullPath: '/api/onboarding/domain/verify'
      preLoaderRoute: typeof ApiOnboardingDomainVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/p2p/token': {
      id: '/api/p2p/token'
      path: '/api/p2p/token'
      fullPath: '/api/p2p/token'
      preLoaderRoute: typeof ApiP2pTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/p2p/signal': {
      id: '/api/p2p/signal'
      path: '/api/p2p/signal'
      fullPath: '/api/p2p/signal'
      preLoaderRoute: typeof ApiP2pSignalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAuthStartRoute: ApiAuthStartRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAssetsEnrollRoute: ApiAssetsEnrollRoute,
  ApiAssetsHeartbeatRoute: ApiAssetsHeartbeatRoute,
  ApiAssetsLiveRoute: ApiAssetsLiveRoute,
  ApiAuthVerifyRoute: ApiAuthVerifyRoute,
  ApiOnboardingDomainVerifyRoute: ApiOnboardingDomainVerifyRoute,
  ApiP2pSignalRoute: ApiP2pSignalRoute,
  ApiP2pTokenRoute: ApiP2pTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
